

spring:
  datasource:
    driverClassName:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: admin

mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9000
